### 第一批数据 20190628

In [1]:
from main import *

Using TensorFlow backend.


In [2]:
image_path ='/data/maze/3D_An_Seg_20190628/01.CVAImage/'
an_path = '/data/maze/3D_An_Seg_20190628/03.Aneurysms/'
vessel_path = '/data/maze/3D_An_Seg_20190628/02.CVAVesselMask/'
save_path = '/home/maze/USAL/libs/data'

(x_train, labels_train), (x_test, labels_test), (x_val, labels_val), data_seperate = generate_data(ImageIo, NumpyIo, data_load_path, drop_data_list = drop_data_list, block_size = 64, save = True, save_path = save_path)

load data from the source dir:  ['/data/maze/3D_An_Seg_20190628/01.CVAImage/', '/data/maze/3D_An_Seg_20190628/03.Aneurysms/', '/data/maze/3D_An_Seg_20190628/02.CVAVesselMask/']
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000002.T0001Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000005.T0001Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000006.T0002Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000009.T0002Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000012.T0001Aneurysms.mha
an #:  1
an #:  2
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000018.T0001Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000022.T0001Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000023.T0001Aneurysms.mha
an #:  1
an #:  2
processing:  /data/maze/3D_An

an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000224.T0003Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000225.T0001Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000229.T0001Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000232.T0001Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000234.T0002Aneurysms.mha
an #:  1
an #:  2
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000235.T0003Aneurysms.mha
an #:  1
an #:  2
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000239.T0001Aneurysms.mha
an #:  1
an #:  2
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000242.T0002Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000243.T0001Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000244.T0003Aneurysms.mha
an 

an #:  1
an #:  2
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000091.T0001Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000131.T0002Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000161.T0002Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000191.T0001Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000191.T0002Aneurysms.mha
an #:  1
an #:  2
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000201.T0002Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000211.T0001Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000211.T0002Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000231.T0002Aneurysms.mha
an #:  1
processing:  /data/maze/3D_An_Seg_20190628/03.Aneurysms/A002.P000241.T0001Aneurysms.mha
an #:  1
pro

### 第二批数据 20191202

In [1]:
from main import *

Using TensorFlow backend.


In [ ]:
image_path ='/data/maze/04.AN-AI/01.CVAImage/'
an_path = '/data/maze/04.AN-AI/03.Aneurysms/'
vessel_path = '/data/maze/04.AN-AI/02.CVAVesselMask/'
save_path = '/home/maze/USAL/libs/new_data'

(x_train, labels_train), (x_test, labels_test), (x_val, labels_val), data_seperate = generate_data(ImageIo, NumpyIo, image_path, an_path, vessel_path, drop_list, block_size = 64, save = True, save_path = save_path)

load img from the source dir:  /data/maze/04.AN-AI/01.CVAImage/
A002.P000208 dropped!
A003.P000143 dropped!
load an from the source dir:  /data/maze/04.AN-AI/03.Aneurysms/
A002.P000208 dropped!
A003.P000143 dropped!
load vessel from the source dir:  /data/maze/04.AN-AI/02.CVAVesselMask/
A002.P000208 dropped!
A003.P000143 dropped!
processing:  /data/maze/04.AN-AI/03.Aneurysms/A002.P000002.D01.S003Aneurysms.mha
an #:  1
processing:  /data/maze/04.AN-AI/03.Aneurysms/A002.P000005.D01.S001Aneurysms.mha
an #:  1
processing:  /data/maze/04.AN-AI/03.Aneurysms/A002.P000006.D01.S001Aneurysms.mha
an #:  1
processing:  /data/maze/04.AN-AI/03.Aneurysms/A002.P000009.D01.S003Aneurysms.mha
an #:  1
processing:  /data/maze/04.AN-AI/03.Aneurysms/A002.P000012.D01.S001Aneurysms.mha
an #:  1
an #:  2
processing:  /data/maze/04.AN-AI/03.Aneurysms/A002.P000018.D01.S001Aneurysms.mha
an #:  1
processing:  /data/maze/04.AN-AI/03.Aneurysms/A002.P000022.D01.S004Aneurysms.mha
an #:  1
processing:  /data/maze/04.AN

In [1]:
from main import *
import numpy as np

image_path ='/data/maze/04.AN-AI/01.CVAImage/'
an_path = '/data/maze/04.AN-AI/03.Aneurysms/'
vessel_path = '/data/maze/04.AN-AI/02.CVAVesselMask/'
save_path = '/home/maze/USAL/libs/new_data'

drop_img_list = ['/data/maze/04.AN-AI/01.CVAImage/A002.P000208.D01.S004CVAImage.mha', 
            '/data/maze/04.AN-AI/01.CVAImage/A003.P000143.D01.S001CVAImage.mha']
drop_an_list = ['/data/maze/04.AN-AI/03.Aneurysms/A002.P000208.D01.S004Aneurysms.mha', 
           '/data/maze/04.AN-AI/03.Aneurysms/A003.P000143.D01.S001Aneurysms.mha']
drop_vessel_list = ['/data/maze/04.AN-AI/02.CVAVesselMask/A002.P000208.D01.S004CVAVesselMask.mha', 
              '/data/maze/04.AN-AI/02.CVAVesselMask/A003.P000143.D01.S001CVAVesselMask.mha']

print('load img from the source dir: ', image_path)
img_dir_list = get_file_dir_lists(image_path, drop_img_list)
print('load an from the source dir: ', an_path)
an_dir_list = get_file_dir_lists(an_path, drop_an_list)
print('load vessel from the source dir: ', vessel_path)
vessel_dir_list = get_file_dir_lists(vessel_path, drop_vessel_list)
        
img_train_list, img_val_list, img_test_list = split_dataset(img_list = img_dir_list, split_id = -22)
an_train_list, an_val_list, an_test_list = split_dataset(img_list = an_dir_list, split_id = -23)
vessel_train_list, vessel_val_list, vessel_test_list = split_dataset(img_list = vessel_dir_list, split_id = -27)
        
x_train = []
labels_train = []
x_test = []
labels_test = []
x_val = []
labels_val = []
data_seperate = []
i = 0
print('processing: ', an_train_list[i])
# read the whole image, an_mask and vessel as array
img_array = ImageIo().load(img_train_list[i])
mask_array = ImageIo().load(an_train_list[i])
vessel_array = ImageIo().load(vessel_train_list[i])


small_img_list = []
small_mask_list = []
# normlization raw image array first
img_array = img_norm(img_array, eps = 1e-7)
# nums of An. 1 or 2 or 3
an_nums = int(np.max(mask_array))
for i in range(an_nums):
    print('an #: ', str(i+1))
    # all index for one an            
    one_an_index = np.where(mask_array == (i+1))
    one_an_array = np.array(one_an_index)    # tuple to array
    one_an_array = np.transpose(one_an_array)    # transpose to (n, 3)
    for j in range(len(one_an_array)):
        x = one_an_array[j][0]
        y = one_an_array[j][1]
        z = one_an_array[j][2]
        vessel_array[x, y, z] = 2
    x_mean = get_label_mean(input_tuple = one_an_index, dim = 0)
    y_mean = get_label_mean(input_tuple = one_an_index, dim = 1)
    z_mean = get_label_mean(input_tuple = one_an_index, dim = 2)
    one_an_center = [x_mean, y_mean, z_mean]
    center_int = [int(round(j)) for j in one_an_center]

Using TensorFlow backend.


load img from the source dir:  /data/maze/04.AN-AI/01.CVAImage/
/data/maze/04.AN-AI/01.CVAImage/A002.P000208.D01.S004CVAImage.mha  dropped!
/data/maze/04.AN-AI/01.CVAImage/A003.P000143.D01.S001CVAImage.mha  dropped!
load an from the source dir:  /data/maze/04.AN-AI/03.Aneurysms/
/data/maze/04.AN-AI/03.Aneurysms/A002.P000208.D01.S004Aneurysms.mha  dropped!
/data/maze/04.AN-AI/03.Aneurysms/A003.P000143.D01.S001Aneurysms.mha  dropped!
load vessel from the source dir:  /data/maze/04.AN-AI/02.CVAVesselMask/
/data/maze/04.AN-AI/02.CVAVesselMask/A002.P000208.D01.S004CVAVesselMask.mha  dropped!
/data/maze/04.AN-AI/02.CVAVesselMask/A003.P000143.D01.S001CVAVesselMask.mha  dropped!
processing:  /data/maze/04.AN-AI/03.Aneurysms/A002.P000002.D01.S003Aneurysms.mha
an #:  1


In [4]:
one_an_index

(array([199, 199, 199, ..., 218, 218, 218]),
 array([266, 266, 266, ..., 280, 281, 281]),
 array([116, 117, 118, ..., 118, 117, 118]))

In [5]:
one_an_array

array([[199, 266, 116],
       [199, 266, 117],
       [199, 266, 118],
       ...,
       [218, 280, 118],
       [218, 281, 117],
       [218, 281, 118]])

In [6]:
print(np.mean(one_an_index[0]), np.mean(one_an_index[1]), np.mean(one_an_index[2]))

208.78095238095239 269.9013431013431 116.59804639804639


In [8]:
print(np.mean(one_an_array, axis = 0))

[208.78095238 269.9013431  116.5980464 ]


In [10]:
mean_dims = np.mean(one_an_array, axis = 0)
type(mean_dims)

numpy.ndarray

In [13]:
mydict = {}
for i in range(len(mean_dims)):
    key = 'dim' + str(i+1)
    value = mean_dims[i]
    mydict.update({key: value})

In [14]:
mydict

{'dim1': 208.78095238095239,
 'dim2': 269.9013431013431,
 'dim3': 116.59804639804639}

In [15]:
mydict['dim1']

208.78095238095239

In [17]:
drop_list = ['A003.P000143']
drop_img_list = ['/data/maze/04.AN-AI/01.CVAImage/A002.P000208.D01.S004CVAImage.mha', 
            '/data/maze/04.AN-AI/01.CVAImage/A003.P000143.D01.S001CVAImage.mha']
drop_an_list = ['/data/maze/04.AN-AI/03.Aneurysms/A002.P000208.D01.S004Aneurysms.mha', 
           '/data/maze/04.AN-AI/03.Aneurysms/A003.P000143.D01.S001Aneurysms.mha']
drop_vessel_list = ['/data/maze/04.AN-AI/02.CVAVesselMask/A002.P000208.D01.S004CVAVesselMask.mha', 
              '/data/maze/04.AN-AI/02.CVAVesselMask/A003.P000143.D01.S001CVAVesselMask.mha']

In [18]:
for name in drop_list:
    for i in range(len(drop_img_list)):
        if name in drop_img_list[i]:
            drop_img_list.remove(drop_img_list[i])

In [21]:
drop_vessel_list

['/data/maze/04.AN-AI/02.CVAVesselMask/A002.P000208.D01.S004CVAVesselMask.mha',
 '/data/maze/04.AN-AI/02.CVAVesselMask/A003.P000143.D01.S001CVAVesselMask.mha']

In [26]:
callbacks = 111
if callbacks != None:
    print('ok')
elif callbacks == None:
    print('no callbakcs')

ok


In [52]:
import random
random.randint(1,3)

3

In [59]:
for i in range(0,10):
    print(random.choice(['xy', 'yz', 'xz']))

yz
xy
xz
xz
yz
xz
xy
xy
xy
xz


### 测试2d_to_3d_image_generator

In [1]:
import sys
sys.path.append('/home/maze/USAL/libs/')
import os
import numpy as np
import random
from data_io.numpy_io import NumpyIo
from mappers.generator_keras import keras_image_generator_2D
from keras.utils import np_utils

data_save_path = '/home/maze/USAL/libs/new_data'
# load dataset
numpyIo = NumpyIo()
x_train = numpyIo.load(path = os.path.join(data_save_path, 'x_train.npy'))
labels_train = numpyIo.load(path = os.path.join(data_save_path, 'labels_train.npy'))
x_test = numpyIo.load(path = os.path.join(data_save_path, 'x_val.npy'))
labels_test = numpyIo.load(path = os.path.join(data_save_path, 'labels_val.npy'))

def image_generator_2Dto3D(data, label, input_generator, class_num, aug_planes = ['xy', 'zy', 'xz'], batch_size = 8, shuffle=True):  #Input dim (n,64,64,64)
    data = np.squeeze(data)
    xy_data = data
    xy_label = label
    xy_batch = input_generator.flow(xy_data, xy_label, batch_size=batch_size, shuffle = shuffle)
    zy_data = data.transpose(0,3,2,1)
    zy_label = label.transpose(0,3,2,1)
    zy_batch = input_generator.flow(zy_data, zy_label, batch_size=batch_size, shuffle = shuffle)
    xz_data = data.transpose(0,1,3,2)
    xz_label = data.transpose(0,1,3,2)
    xz_batch = input_generator.flow(xz_data, xz_label, batch_size=batch_size, shuffle = shuffle)
    while True:
        plane = random.choice(aug_planes)
        if plane == 'xy' or plane == 'yx':
            data_batch, label_batch = next(xy_batch)
            yield(np.expand_dims(data_batch, axis=-1), np_utils.to_categorical(label_batch, class_num))
        elif plane == 'yz' or plane == 'zy':
            data_batch, label_batch = next(zy_batch)
            data_batch = data_batch.transpose(0,3,2,1)
            label_batch = label_batch.transpose(0,3,2,1)
            yield(np.expand_dims(data_batch, axis=-1), np_utils.to_categorical(label_batch, class_num))
        elif plane == 'xz' or plane == 'zx':
            data_batch, label_batch = next(xz_batch)
            data_batch = data_batch.transpose(0,1,3,2)
            label_batch = label_batch.transpose(0,1,3,2)
            yield(np.expand_dims(data_batch, axis=-1), np_utils.to_categorical(label_batch, class_num))

Using TensorFlow backend.


load  /home/maze/USAL/libs/new_data/x_train.npy  completed!
load  /home/maze/USAL/libs/new_data/labels_train.npy  completed!
load  /home/maze/USAL/libs/new_data/x_val.npy  completed!
load  /home/maze/USAL/libs/new_data/labels_val.npy  completed!


In [2]:
keras_datagen = keras_image_generator_2D()
gen = image_generator_2Dto3D(data = x_train, label = labels_train, input_generator = keras_datagen, class_num = 3)

In [3]:
gen

<generator object image_generator_2Dto3D at 0x7f843c68f9e8>

In [14]:
(x, y) = next(gen)

yz


In [28]:
x.shape

(8, 64, 64, 64, 1)

In [29]:
y.shape

(8, 64, 64, 64, 3)

In [29]:
A = ['dfdokef', 'need remove', 'keep this', 'dont ok', 'this fine', 'remove this', 'that good']
B = ['ok', 'remove']

In [30]:
for name in B:
    A = list(filter(lambda x: (name not in x), A))
    print(A)
print(A)

['need remove', 'keep this', 'this fine', 'remove this', 'that good']
['keep this', 'this fine', 'that good']
['keep this', 'this fine', 'that good']
